sudo: false
language: cpp
matrix:
  include:
  - compiler: gcc
  - compiler: clang
    env: QMAKESPEC=linux-clang
matrix:
  include:
  - os: osx
    compiler: clang
    env: PLATFORM=osx PACKTHING=mac
  - os: linux
    compiler: g++
    env: PLATFORM=linux PACKTHING=deb PATH=/home/travis/local/bin:$PATH LD_LIBRARY_PATH=/home/travis/local/lib:$LD_LIBRARY_PATH
before_install: "./scripts/travis.sh"
script:
- qmake
- make -j4
- packthing -j4 $PACKTHING
after_script:
- ls build/staging/
deploy:
  provider: releases
  api_key:
    secure: pXTKmYwykeSD1FSVFvkfR4q91X9AVkNPS2/FKDs+CnWDgFJyDrxsD8D596fLKA3OwbLD7QkXTBj4alhmj7OmcIf56ZZXlKy/O47OfC4JgHjkWYGIbE6CR/UpLRnGS251/zs8NjypnLSk+puiw1lHUqeIBqYGGCzkBN19uaGiyUc=
  file_glob: true
  file: build/staging/propelleride-*
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerIDE
    tags: true
    all_branches: true
