sudo: required
dist: trusty
cache: apt
language: cpp
addons:
  apt:
    packages:
      - help2man
      - lintian
      - cppcheck
      - tree
      - debhelper
      - libudev-dev
      - imagemagick
      - qt5-default
      - libqt5serialport5-dev
matrix:
  fast_finish: true

  include:
  - os: osx
    compiler: clang
    env:
        PLATFORM=osx
        PATH=/Users/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages 

  - os: linux
    compiler: g++
    env:
        PLATFORM=linux
        PATH=/home/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages

  - os: linux
    compiler: clang
    env:
        PLATFORM=linux
        PATH=/home/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages
        QMAKESPEC=linux-clang

  allow_failures:
  - os: linux
    env:
        PLATFORM=rpi
        MNT=/home/travis/mnt

before_install: "[ -f ./.travis/before_install.sh   ] && ./.travis/before_install.sh"
install:        "[ -f ./.travis/install.sh          ] && ./.travis/install.sh"
before_script:  "[ -f ./.travis/before_script.sh    ] && ./.travis/before_script.sh"
script:         "[ -f ./.travis/script.sh           ] && ./.travis/script.sh"
after_script:   "[ -f ./.travis/after_script.sh     ] && ./.travis/after_script.sh"

deploy:
  provider: releases
  api_key:
    secure: pXTKmYwykeSD1FSVFvkfR4q91X9AVkNPS2/FKDs+CnWDgFJyDrxsD8D596fLKA3OwbLD7QkXTBj4alhmj7OmcIf56ZZXlKy/O47OfC4JgHjkWYGIbE6CR/UpLRnGS251/zs8NjypnLSk+puiw1lHUqeIBqYGGCzkBN19uaGiyUc=
  file_glob: true
  file: propelleride-*
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerIDE
    tags: true
    all_branches: true
