language: cpp
matrix:
  include:
  - compiler: gcc
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-qmake qtbase5-dev zlib1g-dev cppcheck
- qmake -qt=qt5 -v
script:
- QMAKE_OPTS="-qt=qt5" make deb -j4
after_script:
- pushd src
- cppcheck --enable=all -q `git ls-files *.cpp *.c`
- pushd openspin/repo
- cppcheck --enable=all -q `git ls-files *.cpp`
deploy:
  provider: releases
  api_key:
    secure: pXTKmYwykeSD1FSVFvkfR4q91X9AVkNPS2/FKDs+CnWDgFJyDrxsD8D596fLKA3OwbLD7QkXTBj4alhmj7OmcIf56ZZXlKy/O47OfC4JgHjkWYGIbE6CR/UpLRnGS251/zs8NjypnLSk+puiw1lHUqeIBqYGGCzkBN19uaGiyUc=
  file_glob: true
  file: staging/propelleride-*.deb
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerIDE
    tags: true
    all_branches: true
