language: cpp

matrix:
    include:
        - compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqt4-opengl-dev zlib1g-dev cppcheck
  - qmake -v

script:
  - make
