language: cpp

matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: QMAKESPEC=unsupported/linux-clang

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev zlib1g-dev cppcheck

script:
  - cd ide
  - qmake
  - make
