sudo: required
language: cpp
matrix:
  include:
  - compiler: gcc
  - compiler: clang
    env: QMAKESPEC=linux-clang
matrix:
  include:
  - os: osx
    compiler: clang
    env:
        PLATFORM=osx PACKTHING=mac
        QT_BIN=/usr/local/opt/qt5/bin:$HOME/local/bin
        QT_LIB=/usr/local/opt/qt5/lib
  - os: linux
    compiler: g++
    env:
        PLATFORM=linux PACKTHING=deb
        QT_BIN=/home/travis/local/bin:$HOME/local/bin
        QT_LIB=/home/travis/local/lib
  - os: linux
    compiler: clang
    env:
        PLATFORM=linux PACKTHING=deb
        QT_BIN=/home/travis/local/bin:$HOME/local/bin
        QT_LIB=/home/travis/local/lib
        QMAKESPEC=linux-clang
install: "./scripts/travis/install.sh"
script:
- export PATH=$QT_BIN:$PATH
- export LD_LIBRARY_PATH=$QT_LIB:$LD_LIBRARY_PATH
- sudo -E packthing -j $PACKTHING
after_script: "./scripts/travis/after_script.sh"
deploy:
  provider: releases
  api_key:
    secure: pXTKmYwykeSD1FSVFvkfR4q91X9AVkNPS2/FKDs+CnWDgFJyDrxsD8D596fLKA3OwbLD7QkXTBj4alhmj7OmcIf56ZZXlKy/O47OfC4JgHjkWYGIbE6CR/UpLRnGS251/zs8NjypnLSk+puiw1lHUqeIBqYGGCzkBN19uaGiyUc=
  file_glob: true
  file: build/staging/propelleride-*
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerIDE
    tags: true
    all_branches: true
