os: MinGW
clone_depth: 200

environment:
    QTDIR: C:\Qt\5.4\mingw491_32
    MINGW: C:\Qt\Tools\mingw491_32
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.x" # currently 2.7.9
    PYTHON_ARCH: "32"

configuration: Release

install:
- git submodule update --init --recursive
- set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin;%PYTHON%;%PYTHON%\Scripts;
- python --version
- pip install packthing
- pip install Pillow
- choco install -y InnoSetup

build_script:
- qmake -r
- mingw32-make -j4
- packthing -j4 win

deploy:
  release: $(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: GXCflmAAS74HVbfY3BV+6wN9HZ6qzYgrcINy3I4KBrUqsRQZUmoa+APbJbt4NzXb
  artifact: build\staging\propelleride-*.exe
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true